version: '2'
services:
    test_jhipster-app:
        image: test_jhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://test_jhipster-mysql:3306/test_jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    test_jhipster-mysql:
        extends:
            file: mysql.yml
            service: test_jhipster-mysql
